export { Home } from './Home'
export { About } from './About'
export { AddEmployee } from './AddEmployee'
export { EmployeeList } from './EmployeeList'
export { Navbar } from './Navbar'
export { References } from './references/References'
export { UseReducerExample } from './references/UseReducerExample'
export { UseCallbackExample } from './references/UseCallbackExample'
export { UseMemoExample } from './references/UseMemoExample'
export { ReduxExample } from './references/ReduxExample'
export {UseContextExample} from './references/UseContextExample'
export {HOCExample} from './references/HOCExample'
export {ListExample} from './references/ListExample'